### ISSUE TITLE
Where can we see updated new of the coin?

### ISSUE THREAD

**Issue by PJEstrada** [ucacoin/Ucacoin2#3]
I'm researching about it but I cannot find any relevant new on this year. Is this project dead?

**Comment by ucacoin** [comment]
No, it's not dead

**Comment by PJEstrada** [comment]
How can I contribute?

**Comment by madlord19** [comment]
> No, it's not dead

its dead man.
the whitepaper is missed...why you lie 
no news for a long time
you scammed early investors with atm + mining 
so why you say its not dead??????

**Comment by madlord19** [comment]
check whitepaper to see
https://ucacoin.com/#!/white 
and also roadmap 
https://unitedcryptoalliance.com/roadmap/

**Comment by PJEstrada** [comment]
Thanks @madlord19 

@ucacoin any feedback on those comments?

**Comment by madlord19** [comment]
my friend this team has no idea about crypto....they will not answer.
Everyone has dissapeared, search for verway , try to find any leader of verway(in what ever country) ......to get answers.....
im afraid you wont find anyone...all are hiding....propably afraid 
now verway is sold....
its funny

**Comment by ucacoin** [comment]
We are currently preparing a new release, please be patient one more time

**Comment by ucacoin** [comment]
Closing for now as 3.4.0 is released.
